# Generated by Django 5.1.7 on 2025-03-20 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('text', models.CharField(max_length=3000000)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_guilds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
