# Generated by Django 5.1.7 on 2025-03-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CookieTracker', '0002_alter_post_poster_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048)),
            ],
        ),
    ]
