# Generated by Django 5.1.7 on 2025-03-21 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CookieTracker', '0003_forum'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='forum',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CookieTracker.forum'),
            preserve_default=False,
        ),
    ]
